---
# Copyright (c) 2024 2025 Oracle and/or its affiliates.
# This software is made available to you under the terms of the Universal Permissive License (UPL), Version 1.0.
# The Universal Permissive License (UPL), Version 1.0 (see COPYING or https://oss.oracle.com/licenses/upl)
# See LICENSE.TXT for details.


- name: Get multipath disk lun id
  hosts: kvm
  order: sorted
  vars_files:
    - default_vars.yml
    - oci_vars.yml
  become: true
  gather_facts: false

  tasks:

    - name: Get multipath disk information # noqa: run-once[task]
      ansible.builtin.command: multipath -ll
      register: multipath_output
      changed_when: multipath_output != 0
      run_once: true

    - name: Extract LUN IDs # noqa: run-once[task]
      ansible.builtin.set_fact:
        lun_ids: "{{ multipath_output.stdout_lines | select('search', '^[a-f0-9]') | map('split', ' ') | map(attribute=0) | list }}"
      run_once: true

    - name: Display LUN IDs # noqa: run-once[task]
      ansible.builtin.debug:
        msg: "LUN IDs: {{ lun_ids }}"
      run_once: true
      when: debug_enabled

    - name: "Add lun_ids to dummy host" # noqa: run-once[task]
      ansible.builtin.add_host:
        name: "LUN_IDS_HOLDER"
        lun_ids: "{{ lun_ids }}"
      run_once: true

- name: Add storage domain
  hosts: engine
  vars_files:
    - default_vars.yml
    - oci_vars.yml
  vars:
    ansible_python_interpreter: "/usr/bin/{{ ovirt_python_version }}"

  tasks:

    - name: Connect to the OLVM Engine application # noqa: syntax-check[unknown-module]
      ovirt.ovirt.ovirt_auth:
        url: "{{ engine_url }}"
        username: "{{ engine_user }}"
        password: "{{ engine_pass }}"
        ca_file: "{{ ansible_env.HOME + '/pki-resource' }}"
        insecure: true
      when: ovirt_auth is undefined or not ovirt_auth
      register: auth_connection
      tags:
        - always

    - name: Print first lun_id in the list
      ansible.builtin.debug:
        msg: "{{ hostvars['LUN_IDS_HOLDER']['lun_ids'][0] }}"
      when: debug_enabled

    - name: Create storage domain
      ovirt.ovirt.ovirt_storage_domain:
        auth: "{{ ovirt_auth }}"
        data_center: Default
        domain_function: data
        fcp:
          lun_id: "{{ hostvars['LUN_IDS_HOLDER']['lun_ids'][ansible_loop.index0] }}"
        host: "olkvm0{{ ansible_loop.index0 + 1 }}"
        name: "amd-storage-domain-0{{ ansible_loop.index0 + 1 }}"
        timeout: 2200
        poll_interval: 10
      loop: "{{ groups['kvm'] }}"
      loop_control:
        extended: true

    - name: Disconnect from the OLVM Engine application
      ovirt.ovirt.ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always
