---
# Copyright (c) 2024 2025 Oracle and/or its affiliates.
# This software is made available to you under the terms of the Universal Permissive License (UPL), Version 1.0.
# The Universal Permissive License (UPL), Version 1.0 (see COPYING or https://oss.oracle.com/licenses/upl)
# See LICENSE.TXT for details.

- name: Upload disk image to data storage
  hosts: olvm

  vars_files:
    - default_vars.yml

  tasks:

    - name: Download ca-cert
      ansible.builtin.get_url:
        url: "https://{{ engine_fqdn }}/ovirt-engine/services/pki-resource?resource=ca-certificate&format=X509-PEM-CA"
        dest: /tmp/pki-resource
        mode: '0664'
        validate_certs: false

    - name: Connect to the OLVM Engine application # noqa: syntax-check[unknown-module]
      ovirt.ovirt.ovirt_auth:
        url: "{{ engine_url }}"
        username: "{{ engine_user }}"
        password: "{{ engine_pass }}"
        ca_file: "{{ engine_cafile }}"
        insecure: true
      when: ovirt_auth is undefined or not ovirt_auth
      register: auth_connection
      tags:
        - always

    - name: Add qcow2 image
      ovirt.ovirt.ovirt_disk:
        name: "test-ol9u5"
        auth: "{{ ovirt_auth }}"
        upload_image_path: /tmp/OL9U5_x86_64-kvm-b253.qcow2
        storage_domain: "amd-storage-domain-01"
        wait: true
        bootable: true
      register: image_sleeper


    - name: Print KVM information
      ansible.builtin.debug:
        msg: "{{ image_sleeper }}"

    - name: Disconnect from the OLVM Engine application
      ovirt.ovirt.ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always
