# Copyright (c) 2024 2025 Oracle and/or its affiliates.
# This software is made available to you under the terms of the Universal Permissive License (UPL), Version 1.0.
# The Universal Permissive License (UPL), Version 1.0 (see COPYING or https://oss.oracle.com/licenses/upl)
# See LICENSE.TXT for details.
---

- name: Copy OLVM engine public key to kvm host
  hosts: all
  order: sorted
  vars_files:
    - default_vars.yml
    - oci_vars.yml
  become: true

  tasks:

    - name: Get the engine public key # noqa: run-once[task]
      community.crypto.openssl_publickey:
        path: /tmp/key.pub
        privatekey_path: "/etc/pki/ovirt-engine/keys/engine_id_rsa"
        format: OpenSSH
      delegate_to: "{{ groups['engine'][0] }}"
      run_once: true

    - name: Fetch engine public key file from server # noqa: run-once[task]
      ansible.builtin.fetch:
        src: "/tmp/key.pub"
        dest: "buffer/engine-key.pub"
        flat: true
      delegate_to: "{{ groups['engine'][0] }}"
      run_once: true

    - name: Copy public key to each destination # noqa: run-once[task]
      ansible.posix.authorized_key:
        user: "root"
        state: present
        key: "{{ lookup('file', 'buffer/engine-key.pub') }}"
      delegate_to: "{{ item }}"
      loop: "{{ groups['kvm'] }}"
      run_once: true

    - name: Download ol9 ova image # noqa: run-once[task]
      ansible.builtin.get_url:
        url: "{{ base_image_url }}"
        dest: "/tmp/{{ base_image_name }}"
        checksum: "sha256:{{ base_image_sha }}"
        mode: "0664"
      vars:
        base_image_name: OL9U5_x86_64-olvm-b253.ova
        base_image_url: https://yum.oracle.com/templates/OracleLinux/OL9/u5/x86_64/{{ base_image_name }}
        base_image_sha: dc5befa484c9aeb51fb0244d5926d53ab482453bd702512066734d8cb2c20600
      delegate_to: "{{ groups['kvm'] | sort | first }}"
      run_once: true
      when: copy_ova_template
